/**
 * Generated by SFJ 1.0.0.558
 * Copyright (C) 2014 imoco.org
 */

package cn.myapp.util.http;

public interface HttpCallBack {

	// public abstract void onProgress(int p1);

	// public abstract void onRequestCanceled();

	public abstract void onRequestEnd(String buf);

	public abstract void onRequestFailed();

	// public abstract void onRequestStart();

}
