/**
 * Generated by SFJ 1.0.0.558
 * Copyright (C) 2014 imoco.org
 */

package cn.myapp.util.http;

import android.widget.ImageView;

public class ImageRequest extends Task {
	private String mUrl;
	private ImageView imageview;

	public String getmUrl() {
		return mUrl;
	}

	public void setmUrl(String mUrl) {
		this.mUrl = mUrl;
	}

	public ImageRequest(String imgUrl, ImageView imageview) {
		super();
		this.mUrl = imgUrl;
		this.imageview = imageview;
	}

	public void runTask() {

		System.out.println("ImageRequest#runTask");
		this.imageview.invalidate();
	}
}
